DROP TABLE IF EXISTS bookstore;

CREATE TABLE bookstore (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  Name VARCHAR(50) NOT NULL,
  Description VARCHAR(550) NOT NULL,
  Author VARCHAR(50) NOT NULL,
  Type VARCHAR(20) NOT NULL,
  Price VARCHAR(250) NOT NULL,
  ISBN VARCHAR(250) NOT NULL,
  DICOUNTCODE VARCHAR(150)
);
